name: Deploy Service Registry to EC2

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t rpyasiru/service-registry:latest .
          docker push rpyasiru/service-registry:latest

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull rpyasiru/service-registry:latest
            docker stop service-registry || true
            docker rm service-registry || true
            docker network create app-network || true
            docker run -d \
              --name service-registry \
              -p 8761:8761 \
              --network app-network \
              -e SPRING_PROFILES_ACTIVE=docker \
              rpyasiru/service-registry:latest
