name: Deploy Service Registry service

on:
  push:
    branches:
      - main

env:
  SERVICE_NAME: service-registry
  IMAGE_NAME: rpyasiru/service-registry:latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      - name: Push Docker image
        run: docker push $IMAGE_NAME

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }} # e.g. ec2-user or ubuntu
          key: ${{ secrets.EC2_KEY }}  # should be the entire contents of your .pem file
          port: 22
          script: |
            docker pull $IMAGE_NAME
            docker stop $SERVICE_NAME || true
            docker rm $SERVICE_NAME || true
            docker run -d \
              --name $SERVICE_NAME \
              -p 8761:8761 \
              $IMAGE_NAME
